---
- name: Launch a Tensorflow - ROCm5 Service Using Docker
  hosts: docker-nodes
  tasks:
  - name:
    docker_container:
      name: tensorflow
      state: started
      restart: true
      image: "{{ docker_image }}"
      networks:
        - name: "{{ docker_network_name }}"
      devices:
        - "/dev/kfd"
        - "/dev/dri"
      ipc_mode: host
      shm-size: 16G
      groups:
        - video
      capabilities:
        - SYS_PTRACE
      security_opts:
        - seccomp=unconfined
      volumes:
        - /tmp/dockerx:/dockerx
