---
- name: Launch a Tensorflow - ROCm5 Service Using Docker
  hosts: docker-nodes
  tasks:
  - name:
    docker_container:
      name: tensorflow
      state: present
      restart: true
      interactive: yes
      tty: yes
      image: "{{ docker_image }}"
      network_mode: "{{ docker_network_mode }}"
      devices:
        - "/dev/kfd"
        - "/dev/dri"
      ipc_mode: host
      shm_size: 16G
      groups:
        - video
      capabilities:
        - SYS_PTRACE
      security_opts:
        - seccomp=unconfined
      volumes:
        - /tmp/dockerx:/dockerx
